# Generated by Django 5.2.3 on 2025-07-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=20)),
                ('medical_history', models.TextField()),
                ('dob', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
