# Generated by Django 5.2.3 on 2025-07-01 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_patient2_delete_patient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patient2',
            new_name='Patient',
        ),
    ]
